#!/bin/zsh

# Set Git configuration globally
git config --global index.threads "16"
git config --global pack.threads "16"
git config --global grep.threads "16"
git config --global http.postBuffer "524288000"
git config --global protocol.version 2

# Find all Git repositories and store them in an array
ARRAY=( $(find $(brew --prefix) -name .git) )

# Define a function to optimize a Git repository
git_optimize() {
  git optimize
}

# Export the function so that it can be used by parallel
export -f git_optimize

# Use parallel to optimize Git repositories in parallel
echo $ARRAY | tr ' ' '\n' | parallel -j 4 -I{} 'cd {}; git_optimize'

# Perform other tasks (e.g., brew update, upgrade, cleanup)
brew update; brew upgrade; brew cu -a
brew cleanup --prune=all -s
